import React, { useState } from 'react';
import {
  Box,
  Container,
  Grid,
  Paper,
  Typography,
  Card,
  CardContent,
  CardActions,
  Button,
  Chip,
  Avatar,
  Drawer,
  IconButton,
  Divider,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  List,
  ListItem,
  ListItemAvatar,
  ListItemText,
  useTheme,
  useMediaQuery,
  TextField,
  Tooltip,
} from '@mui/material';
import {
  Wallet,
  Share,
  Settings,
  Logout,
  Menu as MenuIcon,
  Close,
  School,
  VerifiedUser,
  ContentCopy,
  QrCode,
  Download,
  OpenInNew,
} from '@mui/icons-material';
import { QRCodeSVG } from 'qrcode.react';
import { jsPDF } from 'jspdf';
import { useAuth } from '../state/AuthContext';
import { useBlockchain } from '../state/BlockchainContext';
import { useCredentials } from '../state/CredentialContext';
import { useNavigate } from 'react-router-dom';
import { toast } from 'react-toastify';

const sidebarItems = [
  { id: 'credentials', label: 'My Credentials', icon: <Wallet /> },
  { id: 'share', label: 'Share Credentials', icon: <Share /> },
  { id: 'settings', label: 'Settings', icon: <Settings /> },
];

const UserWallet = () => {
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('md'));
  const navigate = useNavigate();
  
  const { user, logout, updateProfile } = useAuth();
  const { account, formatAddress } = useBlockchain();
  const { 
    credentialTypes, 
    getCredentialsByRecipient,
    generateShareLink,
  } = useCredentials();

  const [activeSection, setActiveSection] = useState('credentials');
  const [mobileDrawerOpen, setMobileDrawerOpen] = useState(false);
  const [selectedCredential, setSelectedCredential] = useState(null);
  const [shareDialogOpen, setShareDialogOpen] = useState(false);
  const [settingsData, setSettingsData] = useState({
    name: user?.name || '',
    email: user?.email || '',
  });

  const walletAddress = account || user?.walletAddress;
  const myCredentials = getCredentialsByRecipient(walletAddress);

  const handleLogout = () => {
    logout();
    navigate('/');
  };

  const handleShareCredential = (credential) => {
    setSelectedCredential(credential);
    setShareDialogOpen(true);
  };

  const handleCopyLink = () => {
    const link = generateShareLink(selectedCredential?.id);
    navigator.clipboard.writeText(link);
    toast.success('Share link copied to clipboard!');
  };

  const handleDownloadPDF = (credential) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(25, 118, 210);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('VeriChain Certificate', 105, 25, { align: 'center' });
    
    // Content
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text(credential.title, 105, 60, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    
    const typeInfo = credentialTypes.find(t => t.id === credential.credentialType);
    doc.text(`Type: ${typeInfo?.name || credential.credentialType}`, 20, 80);
    doc.text(`Issued By: ${credential.issuerName}`, 20, 90);
    doc.text(`Issued To: ${formatAddress(credential.recipient)}`, 20, 100);
    doc.text(`Issue Date: ${new Date(credential.issuedAt).toLocaleDateString()}`, 20, 110);
    
    if (credential.expiresAt) {
      doc.text(`Expiry Date: ${new Date(credential.expiresAt).toLocaleDateString()}`, 20, 120);
    }
    
    if (credential.description) {
      doc.setFontSize(10);
      const description = doc.splitTextToSize(credential.description, 170);
      doc.text(description, 20, 140);
    }
    
    // Verification section
    doc.setFillColor(76, 175, 80);
    doc.roundedRect(20, 180, 170, 30, 3, 3, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('✓ VERIFIED ON BLOCKCHAIN', 105, 198, { align: 'center' });
    
    // Footer
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(`Token ID: ${credential.tokenId}`, 20, 230);
    doc.text(`Transaction: ${credential.transactionHash || 'N/A'}`, 20, 238);
    doc.text(`IPFS Hash: ${credential.ipfsHash || 'N/A'}`, 20, 246);
    doc.text(`Generated by VeriChain - ${new Date().toISOString()}`, 20, 280);
    
    doc.save(`VeriChain-Certificate-${credential.tokenId}.pdf`);
    toast.success('Certificate downloaded!');
  };

  const handleSaveSettings = async () => {
    try {
      await updateProfile(settingsData);
      toast.success('Profile updated successfully!');
    } catch (error) {
      toast.error('Failed to update profile');
    }
  };

  const Sidebar = () => (
    <Box
      sx={{
        width: 280,
        height: '100%',
        backgroundColor: '#1a1a2e',
        color: 'white',
        p: 3,
      }}
    >
      {/* Profile */}
      <Box sx={{ mb: 4 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 2 }}>
          <Avatar sx={{ width: 48, height: 48, bgcolor: 'secondary.main' }}>
            {user?.name?.charAt(0).toUpperCase()}
          </Avatar>
          <Box>
            <Typography variant="subtitle1" fontWeight={600}>
              {user?.name}
            </Typography>
            <Typography variant="caption" sx={{ color: 'grey.400' }}>
              {user?.email}
            </Typography>
          </Box>
        </Box>
        {walletAddress && (
          <Chip
            label={formatAddress(walletAddress)}
            size="small"
            sx={{ backgroundColor: 'rgba(255,255,255,0.1)', color: 'white' }}
          />
        )}
      </Box>

      <Divider sx={{ borderColor: 'grey.800', mb: 2 }} />

      {/* Menu Items */}
      <List>
        {sidebarItems.map((item) => (
          <ListItem
            key={item.id}
            button
            selected={activeSection === item.id}
            onClick={() => {
              setActiveSection(item.id);
              setMobileDrawerOpen(false);
            }}
            sx={{
              borderRadius: 2,
              mb: 1,
              '&.Mui-selected': {
                backgroundColor: 'secondary.main',
                '&:hover': {
                  backgroundColor: 'secondary.dark',
                },
              },
              '&:hover': {
                backgroundColor: 'rgba(255,255,255,0.1)',
              },
            }}
          >
            <ListItemAvatar>
              <Box sx={{ color: activeSection === item.id ? 'white' : 'grey.400' }}>
                {item.icon}
              </Box>
            </ListItemAvatar>
            <ListItemText 
              primary={item.label}
              primaryTypographyProps={{
                fontWeight: activeSection === item.id ? 600 : 400,
              }}
            />
          </ListItem>
        ))}
      </List>

      <Box sx={{ mt: 'auto', pt: 4 }}>
        <Button
          fullWidth
          variant="outlined"
          startIcon={<Logout />}
          onClick={handleLogout}
          sx={{ 
            color: 'grey.400', 
            borderColor: 'grey.700',
            '&:hover': {
              borderColor: 'grey.500',
              backgroundColor: 'rgba(255,255,255,0.05)',
            }
          }}
        >
          Logout
        </Button>
      </Box>
    </Box>
  );

  const CredentialsContent = () => (
    <>
      <Typography variant="body1" color="text.secondary" sx={{ mb: 3 }}>
        You have {myCredentials.length} credential{myCredentials.length !== 1 ? 's' : ''} in your wallet.
      </Typography>

      {myCredentials.length === 0 ? (
        <Paper sx={{ p: 6, textAlign: 'center' }}>
          <Wallet sx={{ fontSize: 64, color: 'grey.300', mb: 2 }} />
          <Typography variant="h6" color="text.secondary" gutterBottom>
            No credentials yet
          </Typography>
          <Typography variant="body2" color="text.secondary">
            When institutions issue credentials to your wallet address, they will appear here.
          </Typography>
        </Paper>
      ) : (
        <Grid container spacing={3}>
          {myCredentials.map((credential) => {
            const typeInfo = credentialTypes.find(t => t.id === credential.credentialType);
            return (
              <Grid item xs={12} sm={6} md={4} key={credential.id}>
                <Card
                  sx={{
                    height: '100%',
                    display: 'flex',
                    flexDirection: 'column',
                    transition: 'transform 0.2s, box-shadow 0.2s',
                    '&:hover': {
                      transform: 'translateY(-4px)',
                      boxShadow: 4,
                    },
                  }}
                >
                  <Box
                    sx={{
                      background: 'linear-gradient(135deg, #1976d2 0%, #7c4dff 100%)',
                      p: 3,
                      color: 'white',
                    }}
                  >
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1 }}>
                      <Typography variant="h4">{typeInfo?.icon || '📜'}</Typography>
                      <Chip
                        icon={<VerifiedUser sx={{ fontSize: 16, color: 'white !important' }} />}
                        label={credential.isRevoked ? 'Revoked' : 'Verified'}
                        size="small"
                        sx={{
                          backgroundColor: credential.isRevoked ? 'error.main' : 'success.main',
                          color: 'white',
                          '& .MuiChip-icon': { color: 'white' },
                        }}
                      />
                    </Box>
                    <Typography variant="subtitle2" sx={{ opacity: 0.8 }}>
                      {typeInfo?.name || credential.credentialType}
                    </Typography>
                  </Box>
                  <CardContent sx={{ flexGrow: 1 }}>
                    <Typography variant="h6" fontWeight={600} gutterBottom>
                      {credential.title}
                    </Typography>
                    <Typography variant="body2" color="text.secondary" gutterBottom>
                      Issued by: {credential.issuerName}
                    </Typography>
                    <Typography variant="caption" color="text.secondary">
                      {new Date(credential.issuedAt).toLocaleDateString()}
                    </Typography>
                  </CardContent>
                  <CardActions sx={{ p: 2, pt: 0 }}>
                    <Tooltip title="Share">
                      <IconButton size="small" onClick={() => handleShareCredential(credential)}>
                        <Share />
                      </IconButton>
                    </Tooltip>
                    <Tooltip title="Download PDF">
                      <IconButton size="small" onClick={() => handleDownloadPDF(credential)}>
                        <Download />
                      </IconButton>
                    </Tooltip>
                    <Tooltip title="View on Explorer">
                      <IconButton size="small">
                        <OpenInNew />
                      </IconButton>
                    </Tooltip>
                  </CardActions>
                </Card>
              </Grid>
            );
          })}
        </Grid>
      )}
    </>
  );

  const SettingsContent = () => (
    <Paper sx={{ p: 3, maxWidth: 600 }}>
      <Typography variant="h6" fontWeight={600} gutterBottom>
        Profile Settings
      </Typography>
      <Grid container spacing={3}>
        <Grid item xs={12}>
          <TextField
            fullWidth
            label="Full Name"
            value={settingsData.name}
            onChange={(e) => setSettingsData({ ...settingsData, name: e.target.value })}
          />
        </Grid>
        <Grid item xs={12}>
          <TextField
            fullWidth
            label="Email"
            type="email"
            value={settingsData.email}
            onChange={(e) => setSettingsData({ ...settingsData, email: e.target.value })}
          />
        </Grid>
        <Grid item xs={12}>
          <TextField
            fullWidth
            label="Wallet Address"
            value={walletAddress || ''}
            disabled
            helperText="Connect a wallet to update your address"
          />
        </Grid>
        <Grid item xs={12}>
          <Button variant="contained" onClick={handleSaveSettings}>
            Save Changes
          </Button>
        </Grid>
      </Grid>
    </Paper>
  );

  const renderContent = () => {
    switch (activeSection) {
      case 'share':
        setActiveSection('credentials');
        return <CredentialsContent />;
      case 'settings':
        return <SettingsContent />;
      default:
        return <CredentialsContent />;
    }
  };

  return (
    <Box sx={{ display: 'flex', minHeight: 'calc(100vh - 64px)' }}>
      {/* Desktop Sidebar */}
      {!isMobile && <Sidebar />}

      {/* Mobile Drawer */}
      <Drawer
        anchor="left"
        open={mobileDrawerOpen}
        onClose={() => setMobileDrawerOpen(false)}
      >
        <Sidebar />
      </Drawer>

      {/* Main Content */}
      <Box sx={{ flexGrow: 1, p: { xs: 2, md: 4 }, backgroundColor: 'grey.50' }}>
        {/* Mobile Header */}
        {isMobile && (
          <Box sx={{ display: 'flex', alignItems: 'center', mb: 3 }}>
            <IconButton onClick={() => setMobileDrawerOpen(true)} sx={{ mr: 2 }}>
              <MenuIcon />
            </IconButton>
            <Typography variant="h6" fontWeight={600}>
              My Wallet
            </Typography>
          </Box>
        )}

        <Container maxWidth="lg" disableGutters>
          <Typography variant="h4" fontWeight={700} gutterBottom>
            {activeSection === 'credentials' && 'My Credentials'}
            {activeSection === 'share' && 'Share Credentials'}
            {activeSection === 'settings' && 'Settings'}
          </Typography>
          
          {renderContent()}
        </Container>
      </Box>

      {/* Share Dialog */}
      <Dialog 
        open={shareDialogOpen} 
        onClose={() => setShareDialogOpen(false)}
        maxWidth="sm"
        fullWidth
      >
        <DialogTitle>
          <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <Typography variant="h6" fontWeight={600}>
              Share Credential
            </Typography>
            <IconButton onClick={() => setShareDialogOpen(false)}>
              <Close />
            </IconButton>
          </Box>
        </DialogTitle>
        <DialogContent>
          {selectedCredential && (
            <Box sx={{ textAlign: 'center', py: 2 }}>
              <Typography variant="h6" gutterBottom>
                {selectedCredential.title}
              </Typography>
              <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
                Share this credential with employers or verifiers
              </Typography>
              
              {/* QR Code */}
              <Box sx={{ mb: 3, p: 2, backgroundColor: 'white', display: 'inline-block', borderRadius: 2 }}>
                <QRCodeSVG 
                  value={generateShareLink(selectedCredential.id)}
                  size={200}
                  level="H"
                  includeMargin
                />
              </Box>
              
              {/* Share Link */}
              <Box sx={{ display: 'flex', gap: 1, mb: 2 }}>
                <TextField
                  fullWidth
                  value={generateShareLink(selectedCredential.id)}
                  InputProps={{ readOnly: true }}
                  size="small"
                />
                <Button variant="outlined" startIcon={<ContentCopy />} onClick={handleCopyLink}>
                  Copy
                </Button>
              </Box>
            </Box>
          )}
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setShareDialogOpen(false)}>Close</Button>
          <Button 
            variant="contained" 
            startIcon={<Download />}
            onClick={() => selectedCredential && handleDownloadPDF(selectedCredential)}
          >
            Download PDF
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};

export default UserWallet;
